<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shahnozas-MacBook-Air.local" failures="1" tests="4" name="TestNGProject" time="62.954" errors="0" timestamp="2023-02-17T20:26:53 MST">
  <testcase classname="com.exelenter.class05._02_AddEmployeeFromExcel" name="addEmployeeTest" time="7.658"/>
  <testcase classname="com.exelenter.class05._02_AddEmployeeFromExcel" name="addEmployeeTest" time="7.459"/>
  <testcase classname="com.exelenter.class05._02_AddEmployeeFromExcel" name="addEmployeeTest" time="8.424"/>
  <testcase classname="com.exelenter.class05._02_AddEmployeeFromExcel" name="addEmployeeTest" time="21.145">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
        <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.class05._02_AddEmployeeFromExcel.addEmployeeTest(_02_HW_AddEmployee.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
</testsuite> <!-- TestNGProject -->
