<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Shahnozas-MacBook-Air.local" failures="0" tests="5" name="com.exelenter.class05._02_HW_AddEmployee" time="73.500" errors="1" timestamp="2023-02-16T18:28:01 MST" skipped="0">
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="25.502">
    <error message="Employee is not added. Username or ID already exits." type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.class05._02_HW_AddEmployee.addEmployeeTest(_02_HW_AddEmployee.java:69)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </error>
  </testcase> <!-- addEmployeeTest -->
  <system-out/>
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="11.748"/>
  <system-out/>
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="12.102"/>
  <system-out/>
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="12.434"/>
  <system-out/>
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="11.714"/>
  <system-out/>
</testsuite> <!-- com.exelenter.class05._02_HW_AddEmployee -->
